[package]
name = "hyuabot-backend-rust"
version = "1.0.0"
edition = "2021"


[dependencies]
actix-web = "4.2.1"
diesel = { version = "2.0.2", features = ["postgres", "r2d2"] }
diesel_migrations = "2.0.0"
r2d2 = "0.8.10"
lazy_static = "1.4.0"
serde = "1.0.148"
